site_name: VoilaVitamin

theme:
  name: material
  palette:
    primary: light-green
  features:
    - navigation.sections
  logo: assets/vv.svg
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md